### ISSUE TITLE
Tests failures with perl >= 5.22

### ISSUE THREAD

**Issue by eserte** [rocky/Perl-Devel-Trepan#39]
See the fail/pass overview: http://matrix.cpantesters.org/?dist=Devel-Trepan%200.70

The situations is not clear: there are some pass reports even with perl >= 5.22. Looking at some fail reports it seems that Data::Printer is involved here, maybe in conjunction with changes in perl's prototype handling.

**Comment by rocky** [comment]
Thanks. Commit  f480d31 I think should address this. Is there a way you can try the github code in the cpantesters environment?

**Comment by eserte** [comment]
I tried f480d31c3ce628ab28d208a9380620cfc260efe9 with a perl which previously failed, and now it looks OK.

You can always create a development release (i.e. Devel-Trepan-0.70_90 or Devel-Trepan-0.71-TRIAL) --- this will be tested by most CPAN Testers but not installed when using CPAN installers.

**Comment by rocky** [comment]
Release 0.71 addresses the problems you were seeing.
