### ISSUE TITLE
can not debug remotely perl script

### ISSUE THREAD

**Issue by KES777** [rocky/Perl-Devel-Trepan#41]
steps to reproduce:
1. run `perl -d:Trepan script.pl` # got: (trepanpl):
2. server<enter> # got:  Waiting for a connection on port 1954 at address 127.0.0.1...
3. in new console: `telnet 127.0.0.1 1954` # got: 
```
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
0013p(trepanpl): 
```
in server terminal # got: Got connection
4. in the telnet terminal: s<enter>
Now I got flood in both terminals. 
On server side terminal:
```
Protocol error - no length; got 'l
```
On client side terminal:
```
undless (trepanpl) promt
```

**Comment by rocky** [comment]
This is not how you debug remotely. Instead follow the instructions at https://metacpan.org/pod/Devel::Trepan#Invocation the section that starts "For out-of-process (and possibly out-of server) debugging:"

**Comment by KES777** [comment]
I think you should put the link above [here](http://search.cpan.org/~rocky/Devel-Trepan-0.56/lib/Devel/Trepan/CmdProcessor/Command/Server.pm) and to the '? server' command

**Comment by KES777** [comment]
`$ENV{TREPANPL_OPTS}` is a hash ref. That is not obvious from doc how to set up keys to required values. I do next:

```
TREPANPL_OPTS='server' perl -d:Trepan -e0
Unquoted string "server" may clash with future reserved word at (eval 35)[/home/kes/localperl_libs/lib/perl5/Devel/Trepan/Core.pm:125] line 1.
-- main::(-e remapped -e:1 @0x253d6b0)
use Devel::Trepan;
(trepanpl): server
Waiting for a connection on port 1954 at address 127.0.0.1...
After this I can not return to the shell. I should to relogin to remote server... CTRL+C or different any key combinations do not help.
```

**Comment by KES777** [comment]
I have found how this is done: `TREPANPL_OPTS='{ server => 1 }' perl -d:Trepan -e0`
but with this the debugger dies with next error:
```
...
Devel::Trepan::IO::TCPServer /home/kes/perl5/lib/perl5/Devel/Trepan/IO/TCPServer.pm at /home/kes/perl5/lib/perl5/rlib.pm line 14.
if /home/kes/perl5/lib/perl5/Devel/Trepan/IO/FIFOServer.pm at /home/kes/perl5/lib/perl5/rlib.pm line 14.
Use of uninitialized value in string eq at /home/kes/perl5/lib/perl5/Devel/Trepan/Core.pm line 195.
Use of uninitialized value in string eq at /home/kes/perl5/lib/perl5/Devel/Trepan/Core.pm line 195.
Use of uninitialized value in string eq at /home/kes/perl5/lib/perl5/Devel/Trepan/Core.pm line 195.
Use of uninitialized value in concatenation (.) or string at /home/kes/perl5/lib/perl5/Devel/Trepan/Core.pm line 213.
Unknown server protocol:  at /home/kes/perl5/lib/perl5/Devel/Trepan/Core.pm line 213.
Compilation failed in require at /home/kes/perl5/lib/perl5/Devel/Trepan.pm line 9.
BEGIN failed--compilation aborted at /home/kes/perl5/lib/perl5/Devel/Trepan.pm line 9.
Compilation failed in require.
BEGIN failed--compilation aborted.
```

digging the sources I have found this:
`TREPANPL_OPTS='{ server => [ "tcp" ] }' perl -d:Trepan -e0`
Please put this minimum info to run debugger into the doc. This is usefull if I want to debug application under uwsgi server. There I put into its site_config.ini next:
```
env = PERL5OPT=d:Trepan
env = TREPANPL_OPTS='{ server => [ "tcp" ] }'

```
Even so the debugger does not work
```
Unable to get Terminal Size. The TIOCGWINSZ ioctl didn't work. The COLUMNS and LINES environment var
iables didn't work. The resize program didn't work. The stty program didn't work. at /home/feelsafe/
perl5/lib/perl5/Devel/Trepan/DB/../../../x86_64-linux-gnu-thread-multi/Term/ReadKey.pm line 451.
```

**Comment by rocky** [comment]
I'm kind of busy right now. Suggest something in a pull request. Thanks.

**Comment by KES777** [comment]
that maybe your debugger suggests is attached to the terminal. The script while running under uwsgi has no terminal at all. 

I suppose the debugger should check 'has it attached to terminal or not'

**Comment by rocky** [comment]
I think the proper way to handle uWSGI is via adding another kind of Processor. See https://github.com/rocky/Perl-Devel-Trepan-BWProcessor for an abortive attempt at yet another kind of protocol.
