### ISSUE TITLE
trepan.pl does not process SIGKILL

### ISSUE THREAD

**Issue by KES777** [rocky/Perl-Devel-Trepan#43]
```
$ ps ax|grep perl
10406 ?        S      0:00 perl -d:Trepan -e0
11198 pts/8    S+     0:00 grep --colour=auto perl
kes@keswork ~/tmp $ kill 10406
kes@keswork ~/tmp $ kill 10406
kes@keswork ~/tmp $ kill 10406
kes@keswork ~/tmp $ kill -kill 10406
kes@keswork ~/tmp $ kill -kill 10406
bash: kill: (10406) - No such process
```
I think this will be better if you allow your debugger finish its work normally and do not force people to stop process unconditionally

**Comment by rocky** [comment]
We follow gdb conventions. See https://metacpan.org/pod/Devel::Trepan::CmdProcessor::Command::Handle

**Comment by KES777** [comment]
Oh, sorry, I have mistake in the title. I mean SIGTERM
