### ISSUE TITLE
Broken link in the doc

### ISSUE THREAD

**Issue by KES777** [rocky/Perl-Devel-Trepan#44]
On [this](https://metacpan.org/pod/Devel::Trepan::CmdProcessor::Command::Info::Signals) page the link is broken:
[handle](https://metacpan.org/pod/Devel::Trepan::CmdProcessor::Handle) for descriptions of the settable fields shown.

You miss '::Command' at it
IS------: https://metacpan.org/pod/Devel::Trepan::CmdProcessor::Handle
Should: https://metacpan.org/pod/Devel::Trepan::CmdProcessor::Command::Handle

**Comment by rocky** [comment]
Ok. Submit a pull request.

**Comment by rocky** [comment]
Commit 3eeee19c addresses this
