### ISSUE TITLE
breakpoint enable failing

### ISSUE THREAD

**Issue by CeleritasCelery** [rocky/Perl-Devel-Trepan#46]
I just got `Devel::Trepan` from CPAN and the breakpoint enable does not work. When I disable a breakpoint and then try to renable it I get the following error

```
(trepanpl): enable 1
Unquoted string "enable" may clash with future reserved word at /nfs/site/home/tjhinckl/scripts/perl_test.pl line 8, <FIN> line 3.
Number found where operator expected at /nfs/site/home/tjhinckl/scripts/perl_test.pl line 8, near "# line 8 "/nfs/site/home/tjhinckl/scripts/perl_test.pl"
 enable 1"
        (Missing operator before 1?)
** syntax error near "# line 8 "/nfs/site/home/tjhinckl/scripts/perl_test.pl"
**  enable 1"
$DB::D[0] = <undef>
```
by looking at `info breakpoints` I only see the disable command, so my guess is that enable is not implemented. However the disable command is listed. whats the point of the disable without an enable? Also the enable command is available in the [documentation](https://metacpan.org/pod/Devel::Trepan::CmdProcessor::Command::Enable) as well.

**Comment by rocky** [comment]
This was fixed in 2a8f368abac21518c3ed219bf32458073b1ce09c . So a workaround is to use the github sources. At some point when I get time I'll put out another release 0.74 which will address this.

**Comment by CeleritasCelery** [comment]
okay. Thank you.

**Comment by rocky** [comment]
[Devel::Trepan 0.74](https://metacpan.org/release/ROCKY/Devel-Trepan-0.74)  has now been released on CPAN. Of the things I work on for open source, I tend to do the things with the highest rating first. So if you star the MetaCPAN link, perhaps I would it have not taken a year and a half for a release. 

Also the subsidiary packages Devel::Trepan::Shell Devel::Trepan::Deparse and Devel::Trepan::Dissassemble are in my opinion very useful add ons.
