### ISSUE TITLE
can't set breakpoint on file

### ISSUE THREAD

**Issue by nkh** [rocky/Perl-Devel-Trepan#49]
(trepanpl): break /home/nadim/perl5/lib/perl5/PBS/Build/Forked.pm
** Subroutine /home/nadim/perl5/lib/perl5/PBS/Build/Forked.pm not found.

according to help location, a breakpoint can be set to a file, that doesn't work. I can't set the breakpoint directly to the function in the module either, it is not exported, but it would be good to be able set it.

**Comment by rocky** [comment]
From "help syntax location": 
>   A location is either some sort of "container" **and a position inside that container.** A container is either a file name or a method name.
>  And a position is either a line number or a bytecode offset. ...
